language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
# install:
#  - pip install .
#  - pip install -r requirements.txt
# command to run tests
notifications:
  slack: blueberryintelli:tYOkF6X29FIuOjOxNTcJclD7
script: python -m unittest discover tests
